### ISSUE TITLE
[BUG] Position Rating will show wrong values after manuell edited subskills until HO is restarted

### ISSUE THREAD

**Issue by vulcan87** [ho-dev/HattrickOrganizer#2185] opened 2024-11-13 21:06 UTC
**Describe the bug**
If i manuell change the Subskill of a player, HO will show incorrect valueschanges at the position until HO is restarted.

I also updated the skill of my goalkeaper. They didnt show a change of the position raiting until HO was restarted.

**To Reproduce**
1. Go to a Player
2. Edit the subskill 
4. See values error

**Screenshots**
First Screenshot after editing Defence (+0,14)
![Screenshot 2024-11-13 220336](https://github.com/user-attachments/assets/c2b4d9b6-54c1-4f00-adfe-5ab09f4ada6e)
Second after restart the programm
![Screenshot 2024-11-13 220430](https://github.com/user-attachments/assets/a16dec92-48a2-4c34-b7fc-bed8e4851e11)

**Platform information:**
 - OS: Windows 
 - Version 8.1 (Build 682)

**Comment by wsbrenk** [comment] 2024-11-24 17:12
same cause as #2153

**Comment by wsbrenk** [comment] 2024-11-24 17:13
should be fixed in current dev version

**Comment by vulcan87** [comment] 2024-11-29 08:42
In the current dev version its calculated & shown directly and correct now.

I just saw that the change isnt shown. But i dont know if this
GK 6.0 --> GK Raiting = 3,72
GK 6.5 --> GK Raiting = 3.97

shouldnt it show the difference llike "3.97 +0.25" after changing a subskill?

**Comment by wsbrenk** [comment] 2024-11-30 16:47
@vulcan87  thanks for your feedback. Concerning your question: Your right, it would be nice if the table would show the effects of your skill changes. The problem is that the skill editor directly stores the new values to the database and with that it overrides the comparison value.
A workaround is to select the previous hrf as comparison base. If the existing previous is not useful load data again to get a better one.

**Comment by vulcan87** [comment] 2024-12-06 09:41
Yeah thats fine for me. at the end you dont change the subskill daily.

But a little other problem occured this week - after get the new training data from ht, all players changed the form. Looks like it shouldnt look in this way.

![grafik](https://github.com/user-attachments/assets/0b4d91f9-1e18-4976-9137-e5b8130c7597)

**Comment by wsbrenk** [comment] 2024-12-06 18:13
Form is now calculated automatically from current tsi and skill values. By adjusting the skill subs you could try to find the subs that will fit to current tsi. See bottom line in Skill editor.

Stamina sub is also calculated and depends especially on player's age. So a negative change is possible.

**Comment by vulcan87** [comment] 2024-12-08 11:57
So i have to guess all the sub raitings because otherwhise the form wouldnt fit?

It has changed to x.99 at almost all players... because i dont know the subskills i have manuelly to edit everyone to .00 because if not,  the x.99 will be calculated in the positions raiting and so on so i got wrong values for raitings and so on. 

And after each donwload of a hrf file the form sub will be reseted to .99 by HO again...

**Comment by wsbrenk** [comment] 2024-12-08 12:15
what you see is a new - i think very useful - feature of the HO. The TSI value depends on the skill values and the form. So if you download new values ho will try to calculate the form sub to reach the current tsi.
If you see a form sub of .99, this will show you that some of your skill subs are too low. By adjusting those skills you could try to fit the estimated tsi value to the current value which are shown in the new skill editor dialog. In this dialog you also can adjust the form sub.

This is not necessary after each download. If you have found the exact values (which only ht will know) and store them, ho will calculated nearly correct form skill values.

**Closed** 2024-12-19 21:34 UTC
Labels: status: needs test
