### ISSUE TITLE
[BUG] Error in download at Create staff stage

### ISSUE THREAD

**Issue by Moshu** [ho-dev/HattrickOrganizer#1913] opened 2023-09-08 07:44 UTC
While performing the download, the process is interrupted by a java.lang.StackOverflowError. The stage in the left bottom corner is "Create staff...". However, I think it occurs for a particular player, since after the error some of the players are missing from my team.

This happens for two of my three teams, Shopska s rakia (664030) and Elaiolado (904313). Each of them have a new player promoted from the youth team shortly before the download, maybe this is the cause, but it worked fine in the past in such conditions.

![Screenshot 2023-09-08 102530](https://github.com/ho-dev/HattrickOrganizer/assets/1288499/3ec823e9-3690-415c-88ba-4d65cd8b789b)

 - OS: Windows 11
 - Version 7.2

The complete log in the error window is:

java.lang.StackOverflowError
	at java.base/java.io.InputStream.<init>(InputStream.java:61)
	at java.base/java.io.FilterInputStream.<init>(FilterInputStream.java:60)
	at java.base/sun.net.www.MeteredStream.<init>(MeteredStream.java:50)
	at java.base/sun.net.www.http.KeepAliveStream.<init>(KeepAliveStream.java:60)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:1014)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:139)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:630)
	at core.net.MyConnector.downloadPlayerDetails(MyConnector.java:432)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1193)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:499)
	at core.model.player.Player.getMotherclubId(Player.java:488)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:501)
	at core.model.player.Player.getMotherclubId(Player.java:488)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:501)
	...

**Comment by manguz** [comment] 2023-09-08 09:01
Yeah, can confirm.
I use 2 seperate instance of HO, one for main team and one for the Anniversary team.
The AT one downloads data correctly, while the main one fails and in the main one I have a new player promoted from youth some days ago.
this Player is already present in the roster in the dB as it was created some days ago when it worked downloading data.

[errorLOG.txt](https://github.com/ho-dev/HattrickOrganizer/files/12557637/errorLOG.txt)

**Comment by tychobrailleur** [comment] 2023-09-08 17:57
I have tried two players in the CHPP example page for playerdetails, one homegrown, one not, and neither come back with the `MotherClub` tag in version 2.9 (which I understand is the version where that tag has been added). Ironically the `MotherClubBonus` tag that used to be returned is also not returned in 2.9.  

@wsbrenk is that a CHPP regression?

**Comment by wsbrenk** [comment] 2023-09-08 21:55
Looks like a bug in the chpp playerdetails file. this was mentioned in the chpp forum. Should be fixed now.

**Comment by wsbrenk** [comment] 2023-09-08 23:32
chpp returns playerdetails Version 1.2 although Version 2.9 was requested - crazy!

**Comment by orrinoAriel** [comment] 2023-09-08 23:42
Hi there!
I'm experiencing the same mentioned issue...
This is the backtrace log error

java.lang.StackOverflowError
	at java.base/com.sun.crypto.provider.GHASH.doFinal(GHASH.java:221)
	at java.base/com.sun.crypto.provider.GHASH.doFinal(GHASH.java:343)
	at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMEngine.doLastBlock(GaloisCounterMode.java:797)
	at java.base/com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1471)
	at java.base/com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:447)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2500)
	at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1659)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1508)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1479)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1064)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:791)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:139)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:630)
	at core.net.MyConnector.downloadPlayerDetails(MyConnector.java:432)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1193)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:503)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
......

After that, these two lines are repeated a lot of times
at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
at core.model.player.Player.getMotherclubId(Player.java:492)


As other guys mentioned, I have a new player recently promoted to the main team.

I tried with the last stable version(7.2.X) and with the last dev version (8.0-r518)

**Comment by wsbrenk** [comment] 2023-09-08 23:48
i just reproducede with my own team. the reason is an error in chpp - i hope with the fix, the next ho version will survive such errors.

**Comment by orrinoAriel** [comment] 2023-09-09 00:35
@wsbrenk i can test it if you wish

**Comment by Moshu** [comment] 2023-09-09 00:35
I have just received this, maybe this was the cause.

_Newsletter from CHPP Admins
Conversation with [CHPP-teles](https://www89.hattrick.org/Club/Manager/?userId=653581)

Hello CHPP devs!

A quick info to announce the last changes on chpp data.
There are new version for some files, especially players and playerdetails
In those files the trainer is no more included if he is not a also player.
To be sure to get the trainer data, for a pure trainer, a player trainer or a hof trainer, you have to fetch the new version of stafflist, and staffavatars to get its avatar.

This change was done to reflect the last changes on trainers in the game.

Have a look at the documentation [(/Community/CHPP/NewDocs/)](https://www89.hattrick.org/Community/CHPP/NewDocs/) and don't forget to update your code when you update the file version!_

**Comment by Moshu** [comment] 2023-09-09 07:58
I tested with the beta version, everything is back to normal. Thank you! :-)

**Closed** 2023-09-09 09:31 UTC
Labels: status: needs test
